# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test' do
  use_frameworks!
  
  pod 'RxSwift', '~> 6.0.0'
  pod 'RxCocoa', '~> 6.0.0'
  pod 'SwiftyJSON', '~> 4.0'
  
  target 'ProjectTests' do
    inherit! :search_paths
    pod 'RxTest', '~> 6.0.0'
    pod 'RxBlocking','~> 6.0.0'
  end
end
